source = ~/.config/hypr/modules-conf/binds.conf
source = ~/.config/hypr/modules-conf/autostart.conf
source = ~/.config/hypr/modules-conf/lookNfeel.conf
source = ~/.config/hypr/modules-conf/animations.conf
source = ~/.config/hypr/modules-conf/windowsNworkspaces.conf
source = ~/.config/hypr/modules-conf/monitors.conf
source = ~/.config/hypr/modules-conf/input.conf
source = ~/.config/hypr/modules-conf/environment.conf
