
#   _                   _   
#  (_)_ __  _ __  _   _| |_ 
#  | | '_ \| '_ \| | | | __|
#  | | | | | |_) | |_| | |_ 
#  |_|_| |_| .__/ \__,_|\__|
#          |_|              
#

input {
    kb_layout = us,fr
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle,compose:rctrl
    kb_rules =

    sensitivity = 0
    accel_profile = flat
}

device {
    name = glorious-model-o-wireless
    sensitivity = 0
    accel_profile = flat
}
