[mgr]
ratio = [1, 3, 4]
linemode = "size_and_mtime"

[manager]
header_height = 0

[preview]
max_width = 1500
max_height = 750

[opener]
edit = [
  { run = 'nvim "$@"',      block = true,  desc = "Neovim" },
  { run = 'codium "$@"',    orphan = true, desc = "VSCodium" },
]
view_image = [
  { run = 'swayimg "$@"',   orphan = true, desc = "Swayimg" },
]
view_document = [
  { run = 'librewolf "$@"', orphan = true, desc = "Librewolf" },
]
editandview_html = [
  { run = 'nvim "$@"',      block = true,  desc = "Neovim" },
  { run = 'codium "$@"',    orphan = true, desc = "VSCodium" },
  { run = 'librewolf "$@"', orphan = true, desc = "Librewolf" },
]

[open]
rules = [
  { mime = "image/*",          use = "view_image" },
  { mime = "application/pdf",  use = "view_document" },
  { url = "*.pdf",             use = "view_document" },
  { url = "*.html",            use = "editandview_html" },
  { mime = "text/*",           use = "edit" },
  { mime = "inode/x-empty",    use = "edit" },
  { url = "*.txt",             use = "edit" },
  { url = "*.json",            use = "edit" },
  { mime = "application/json", use = "edit" },
  { url = "*.sh",              use = "edit" },
  { url = "*.py",              use = "edit" },
  { url = "*.toml",            use = "edit" },
  { url = "*.yaml",            use = "edit" },
  { url = "*.yml",             use = "edit" },
  { url = "*.xml",             use = "edit" },
  { url = "*.csv",             use = "edit" },
  { url = "*.js",              use = "edit" },
  { url = "*.ts",              use = "edit" },
  { url = "*.rs",              use = "edit" },
  { url = "*.go",              use = "edit" },
  { url = "*.c",               use = "edit" },
  { url = "*.h",               use = "edit" },
  { url = "*.cpp",             use = "edit" },
  { url = "*.lua",             use = "edit" },
  { url = "*",                 use = "edit" },
]
